image: node:22

pages:
  script:
  - npm install
  - npm run metadata:generate
  - npm run build
  - mv ./bundle ./public
  - cp --recursive ./website/* ./public/

  artifacts:
    paths:
    - public

  only:
  - master

update-metadata:
  script:
  - git checkout master
  - npm install
  - npm run metadata:update:job